const header = [
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Mắt\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-mat.webp\r\ntab-icon-2\r\n",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Thẩm mỹ vùng mắt</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/cat-mi-mat/\">PT tạo mắt 2 mí</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/nhan-mi-mat/\">Khâu tạo mắt 2 mí</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/lay-mo-mi-mat-tren/\">PT thừa da mí mắt</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/cat-mi-mat-nam/\">Phẫu thuật tạo mắt 2 mí cho nam</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/nang-cung-may/\">PT nâng cung mày</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/sup-mi-mat-bam-sinh/\">PT treo cơ mi</a></li>\n</ul>\n</div>\n<p>&nbsp;</p>\n<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Khắc phục khuyết điểm mắt</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/cay-mo/cay-mo-hoc-mat/\">Ghép mỡ tự thân vùng mắt</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/mo-rong-goc-mat/\">PT vùng quanh mắt</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/phau-thuat-mat-to/\">PT tạo hình mí mắt và vùng xung quanh</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/cat-mi-hong/\">Chỉnh sửa biến chứng sau thẩm mỹ mắt</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mat/lay-mo-mi-mat-tren/\">PT lấy bọng mỡ</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Mũi\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-mui.webp\r\ntab-icon-3",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Thẩm mỹ vùng mũi</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/nang-mui/\">Nâng mũi thẩm mỹ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/nang-mui-han-quoc-kangnam/\">Nâng mũi chất liệu nhân tạo</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/nang-mui-cau-truc/\">Nâng mũi kết hợp chất liệu tự thân</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/nang-mui-sun-suon-kangnam/\">Nâng mũi bằng sụn tự thân</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/phau-thuat-nang-mui-cho-nam-gioi/\">Nâng mũi cho nam</a></li>\n</ul>\n</div>\n<p>&nbsp;</p>\n<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Khắc phục khuyết điểm mũi</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/thu-gon-canh-mui/\">PT thu gọn cánh mũi</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/thu-nho-dau-mui/\">PT thu nhỏ đầu mũi</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/mui-go-lech-phai-lam-sao/\">PT hạ thấp sống mũi gồ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/nang-mui-bi-hong/\">Chỉnh sửa mũi bị hỏng sau nâng</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-mui/tiem-filler-mui/\">Tiêm chất làm đầy nâng mũi</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Khuôn mặt\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-km.webp\r\ntab-icon-4",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Thẩm mỹ hàm mặt</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ham-mat/phau-thuat-got-ham-vline-tai-kangnam/\">PT chỉnh sửa góc hàm</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ham-mat/phau-thuat-ham-ho-mom-tai-kangnam/\">PT chỉnh sửa thân xương hàm</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ham-mat/go-ma-thap/\">PT chỉnh sửa gò má</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ham-mat/phau-thuat-don-cam-v-line/\">PT độn cằm</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ham-mat/phau-thuat-truot-cam-vline-kangnam/\">PT cắt chỉnh sửa cằm (trượt cằm)</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ham-mat/phau-thuat-cuoi-ho-loi/\">PT chữa cười hở lợi</a></li>\n</ul>\n</div>\n<p>&nbsp;</p>\n<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Thẩm mỹ khác</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-moi/cat-moi-trai-tim/\">PT tạo hình môi</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ma-lum/tao-ma-lum-dong-tien-an-toan-tai-kangnam/\">PT tạo má lúm</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cang-da-cay-mo-mat/cang-da-mat/\">PT căng da mặt toàn phần</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cang-da-cay-mo-mat/tre-hoa-mi-young/\">Trẻ hóa da không phẫu thuật</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cang-da-cay-mo-mat/cang-da-mat-bang-chi-collagen/\">Thủ thuật treo chỉ căng da</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cay-mo/cay-mo-mat/\">PT cấy mỡ vùng mặt</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Body\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-body.webp\r\ntab-icon-5",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Thẩm mỹ vòng 1</div>\n<ul>\n<li style=\"list-style-type: none;\">\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-vong-1/nang-nguc-kangnam/\">PT nâng vú bằng túi độn ngực</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-vong-1/nang-nguc-bang-mo-tu-than/\">PT nâng vú bằng chất làm đầy</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-vong-1/treo-nguc-sa-tre/\">PT treo vú sa trễ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-vong-1/thu-gon-nguc-phi-dai/\">PT thu nhỏ vú phì đại</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-vong-1/thu-nho-quang-nhu-hoa/\">PT tái tạo quầng núm vú</a></li>\n</ul>\n</li>\n</ul>\n<div class=\"header_20_0_0__title\">Nâng mông</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-vong-3/nang-mong-noi-soi/\">PT làm to mông bằng túi độn</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-vong-3/nang-mong-bang-mo-tu-than/\">PT cấy mỡ vùng mông</a></li>\n</ul>\n</div>\n<p>&nbsp;</p>\n<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Hút Mỡ</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-bung/\">Hút mỡ bụng toàn phần</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-dui/\">Hút mỡ đùi</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-bap-tay/\">Hút mỡ vùng cánh tay</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-lung/\">Hút mỡ vùng lưng</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-nong-cam/\">Hút mỡ cằm</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-mat/\">Hút mỡ má</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-bap-chan/\">Hút mỡ chân</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/hut-mo-nach/\">Hút mỡ nách</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/tao-hinh-thanh-bung/\">PT tạo hình bụng</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/giam-mo/tao-hinh-thanh-bung-6-mui/\">Tạo bụng 6 múi</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Trẻ hóa\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-trehoa.webp\r\ntab-icon-6",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Trẻ hóa công nghệ cao</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/cay-mo/cay-mo-tu-than/\">Cấy mỡ Nanofat</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cang-da-cay-mo-mat/tre-hoa-mi-young/\">Trẻ hóa da toàn diện 4 trong 1</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/dich-vu-cong-nghe-cao/thermage/\">Trẻ hóa da Thermage FLX</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/dich-vu-cong-nghe-cao/lam-day-ranh-nhan/\">Làm đầy rãnh nhăn</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/nam-tan-nhang/cham-soc-da-chuyen-sau-kangnam/\">Chăm sóc da chuyên sâu</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/dich-vu-cong-nghe-cao/vi-kim-tao-bien/\">Vi kim tảo biển</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Da liễu\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-dalieu.webp\r\ntab-icon-7",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Điều trị da</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/cham-soc-da/dieu-tri-nam/\">Trị nám</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/nam-tan-nhang/laser-picosure-cong-nghe-xoa-tan-nhang-uu-viet/\">Trị tàn nhang</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/seo/tri-seo-loi-lau-nam/\">Trị sẹo lồi</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/seo/cach-tri-seo-ro-lau-nam/\">Trị sẹo rỗ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/mun/tri-mun-tai-kangnam-cong-nghe-nano-skin/\">Điều trị mụn</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/vet-tham/tri-tham-mun/\">Trị thâm bằng laser</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/dich-vu-khac/tay-not-ruoi/\">Tẩy nốt ruồi</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Spa\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-spa.webp\r\ntab-icon-8",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Spa Cao Cấp</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tam-trang/tam-trang-phi-thuyen/\">Tắm trắng phi thuyền</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/phun-xam/phun-xam-moi-dep/\">Phun môi</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/phun-xam/phun-mi-mo-trong-han-quoc/\">Phun mí mở tròng</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/phun-xam/xam-mi-mat/\">Xăm mí mắt</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-long-may/dieu-khac-chan-may/\">Điêu khắc chân mày</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-long-may/phun-theu-chan-may/\">Thêu chân mày</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-moi/phun-xam-plascell/\">Phun xăm thẩm mỹ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-long-may/dieu-khac-chan-may-nam/\">Điêu khắc chân mày nam</a></li>\n</ul>\n</div>\n<p>&nbsp;</p>\n<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Triệt Lông</div>\n<ul>\n<li style=\"list-style-type: none;\">\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/cach-triet-long/triet-long-vinh-vien/\">Triệt lông Diode Laser</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cach-triet-long/tay-long-chan/\">Triệt lông chân</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cach-triet-long/triet-long-mat-vinh-vien/\">Triệt lông mặt</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cach-triet-long/triet-long-nach-vinh-vien/\">Triệt lông nách</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cach-triet-long/triet-long-tay-vinh-vien/\">Triệt lông tay</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/cach-triet-long/triet-ria-mep/\">Triệt ria mép</a></li>\n</ul>\n</li>\n</ul>\n<div class=\"header_20_0_0__title\">Dịch Vụ Khác</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/rung-toc/cay-toc-tu-than/\">Cấy tóc tự thân</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/dich-vu-cong-nghe-cao/don-thai-duong/\">Độn thái dương</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/spa-tham-my/xoa-hinh-xam/\">Xóa xăm</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/hoi-nach/cach-tri-hoi-nach/\">Trị hôi nách</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Nha khoa\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-nhakhoa.webp\r\ntab-icon-9",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Nha khoa thẩm mỹ</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/tu-van-rang-su/boc-rang-su/\">Bọc răng sứ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tu-van-rang-su/dan-su-veneer/\">Mặt dán sứ Veneer</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tu-van-han-rang/tram-rang-tham-my/\">Trám răng thẩm mỹ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tu-van-trang-rang/tay-trang-rang/\">Tẩy trắng răng</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/nha-khoa-tham-my/cau-rang-su/\">Làm cầu răng sứ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tham-my-ham-mat/khac-phuc-cuoi-ho-loi-khong-phau-thuat/\">Chữa cười hở lợi</a></li>\n</ul>\n</div>\n"
    },
    {
        "acf_fc_layout": "menu_sub_fullPC",
        "titlePC": "Giới thiệu\r\n#\r\nhttps://cdn.benhvienthammykangnam.vn/wp-content/themes/SCI_Theme/Module/Header/header_20_0_0/images/dv-gt.webp\r\ntab-icon-1",
        "col1pc": "<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Về thương hiệu Kangnam</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/kien-thuc-lam-dep/benh-vien-chuan-han-quoc-uy-tin-hang-dau-tai-viet-nam/\">Giới thiệu</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/doi-ngu-bac-si/\">Đội ngũ bác sĩ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tin-tuc/cong-nghe-vectra/\">Công nghệ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/khach-hang-kangnam/\">Video dịch vụ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/lien-he/\">Thông tin liên hệ</a></li>\n</ul>\n</div>\n<p>&nbsp;</p>\n<div class=\"header_20_0_0__dropItem\">\n<div class=\"header_20_0_0__title\">Bảng Giá &amp; Chính Sách</div>\n<ul>\n<li><a href=\"https://benhvienthammykangnam.vn/bang-gia-dich-vu-tham-my/cap-nhat-bang-gia-phau-thuat-tham-my-tai-kangnam-moi-nhat/\">Bảng giá dịch vụ thẩm mỹ</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/tin-tuc/chinh-sach-bao-hanh-uy-tin-tai-benh-vien-tham-my-kangnam/\">Chính sách bảo hành</a></li>\n<li><a href=\"https://benhvienthammykangnam.vn/khach-hang-kangnam/\">Hình ảnh trước sau khách hàng</a></li>\n</ul>\n</div>\n"
    }
]

